version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:80"
    env_file: .env
    labels:
      traefik.enable: "true"
      traefik.http.routers.jellyfin.rule: "Host(`smallgroup.${DOMAIN}.com`)"
      traefik.http.routers.jellyfin.tls.certresolver: "letsencrypt"
      traefik.http.routers.jellyfin.tls.domains[0].main: "${DOMAIN}.com"
      traefik.http.routers.jellyfin.tls.domains[0].sans: "*.${DOMAIN}.com"
      traefik.http.services.jellyfin.loadbalancer.server.port: "8000"
